# Generated by Django 3.0.6 on 2020-05-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField()),
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='main.Cartridge')),
            ***REMOVED***,
        ),
    ***REMOVED***
