# Generated by Django 3.0.6 on 2020-05-26 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('manufacturer', models.CharField(choices=[('HP', 'HP'), ('Kyocera', 'Kyocera'), ('Samsung', 'Samsung')], default='HP', max_length=30, verbose_name='Производитель')),
                ('name', models.CharField(db_column='cartridge_name', help_text='Наименование картриджа должно быть уникальным', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Название картриджа')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out', models.BooleanField(choices=[(True, 'Выдача'), (False, 'Поступление')], default=True, verbose_name='Тип передвижения')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='main.Cartridge', verbose_name='Тип картриджа')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Обработка заявки'), ('work', 'В работе'), ('finished', 'Завершён')], default='work', max_length=10, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер заявки')),
                ('finished', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.Cartridge', verbose_name='Картридж')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.Supply', verbose_name='Перемещение')),
            ],
        ),
    ]
