# Generated by Django 3.0.6 on 2020-05-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ***REMOVED***

    operations = [
        migrations.RenameField(
            model_name='cartridge',
            old_name='cartridge_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='name',
            field=models.CharField(db_column='cartridge_name', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Название картриджа'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='cartridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='main.Cartridge', verbose_name='Тип картриджа'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='out',
            field=models.BooleanField(choices=[(True, 'Выдача'), (False, 'Поступление')***REMOVED***, default=True, verbose_name='Тип передвижения'),
        ),
    ***REMOVED***
