# Generated by Django 3.0.6 on 2020-05-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'ordering': ['manufacturer', 'name']},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Обработка заявки'), ('work', 'В работе'), ('finished', 'Завершён')], default='work', max_length=10),
        ),
    ]
