# Generated by Django 3.0.6 on 2020-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='manufacturer',
            field=models.CharField(default='HP', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='out',
            field=models.BooleanField(default=True),
        ),
    ]
