# Generated by Django 3.0.4 on 2020-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ***REMOVED***

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
    ***REMOVED***
