# Generated by Django 3.0.6 on 2020-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200512_1515'),
    ***REMOVED***

    operations = [
        migrations.AddField(
            model_name='supply',
            name='comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='name',
            field=models.CharField(db_column='cartridge_name', help_text='Наименование картриджа должно быть уникальным', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Название картриджа'),
        ),
    ***REMOVED***
