# Generated by Django 3.0.6 on 2020-05-24 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200524_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Обработка заявки'), ('work', 'В работе'), ('finished', 'Завершён')], default='work', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 24, 18, 9, 4, 393856, tzinfo=utc)),
        ),
    ]
