# Generated by Django 3.0.6 on 2020-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200508_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='manufacturer',
            field=models.CharField(choices=[('HP', 'HP'), ('Kyocera', 'Kyocera'), ('Samsung', 'Samsung')], max_length=30),
        ),
    ]
