# Generated by Django 3.0.6 on 2020-05-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200513_2037'),
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(blank=True)),
                ('finished', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField()),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.Cartridge')),
                ('supply', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.Supply')),
            ***REMOVED***,
        ),
    ***REMOVED***
