# Generated by Django 3.0.6 on 2020-05-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ***REMOVED***

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ***REMOVED***
