# Generated by Django 3.0.6 on 2020-05-24 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200524_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
