# Generated by Django 3.0.4 on 2020-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200508_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='manufacturer',
            field=models.CharField(choices=[('HP', 'HP'), ('Kyocera', 'Kyocera'), ('Samsung', 'Samsung')], default='HP', max_length=30),
        ),
    ]
