# Generated by Django 3.0.4 on 2020-05-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200515_0930'),
    ***REMOVED***

    operations = [
        migrations.AddField(
            model_name='supply',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cartridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.Cartridge', verbose_name='Картридж'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.Supply', verbose_name='Перемещение'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ***REMOVED***
