# Generated by Django 3.1.6 on 2021-02-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(verbose_name='ИД сообщения')),
                ('telegram_user_id', models.PositiveIntegerField(verbose_name='ИД пользователя')),
                ('bot_answer_message_id', models.PositiveIntegerField(blank=True, verbose_name='Ответ бота')),
                ('chat_id', models.IntegerField(verbose_name='ИД чата')),
                ('inv_number', models.CharField(max_length=20, verbose_name='Инвентарный номер')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('inv_image', models.ImageField(blank=True, upload_to='', verbose_name='Фото инвентарного номера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Message time')),
            ],
            options={
                'verbose_name': 'Перемещение техники',
                'verbose_name_plural': 'Перемещения техники',
            },
        ),
        migrations.CreateModel(
            name='AdditionalPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(verbose_name='ИД сообщения')),
                ('chat_id', models.IntegerField(verbose_name='ИД чата')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Дополнительное фото')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='telegram.equipmovement', verbose_name='EquipMovement')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
            },
        ),
    ]
